export const DECISION_REASON_CODES = {
  SAFETY_TEMPERATURE: 'SAFETY_TEMPERATURE',
  SAFETY_VOLTAGE: 'SAFETY_VOLTAGE',
  SOC_AT_MAX: 'SOC_AT_MAX',
  SOC_AT_MIN: 'SOC_AT_MIN',
  FREQUENCY_LOW: 'FREQUENCY_LOW',
  FREQUENCY_HIGH: 'FREQUENCY_HIGH',
  RENEWABLE_SURPLUS: 'RENEWABLE_SURPLUS',
  ENERGY_DEFICIT: 'ENERGY_DEFICIT',
  FORECASTED_SURPLUS: 'FORECASTED_SURPLUS',
  FORECASTED_DEFICIT: 'FORECASTED_DEFICIT',
  BALANCED_SYSTEM: 'BALANCED_SYSTEM',
  INSUFFICIENT_DATA: 'INSUFFICIENT_DATA',
  ENGINE_ERROR: 'ENGINE_ERROR',
} as const;

export const DISPATCH_ACTIONS = {
  CHARGE: 'CHARGE',
  DISCHARGE: 'DISCHARGE',
  HOLD: 'HOLD',
  FREQUENCY_SUPPORT: 'FREQUENCY_SUPPORT',
} as const;

export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_CONFIGURATION: 'INVALID_CONFIGURATION',
  INVALID_TELEMETRY: 'INVALID_TELEMETRY',
  INSUFFICIENT_HISTORY: 'INSUFFICIENT_HISTORY',
  ENGINE_TIMEOUT: 'ENGINE_TIMEOUT',
  ENGINE_FAILURE: 'ENGINE_FAILURE',
  ENGINE_INVALID_RESPONSE: 'ENGINE_INVALID_RESPONSE',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;
